name: Third_workflow
on: push

jobs: 
  myjob: 
    runs-on: ubuntu-latest
    steps: 
      - name: First step
        run: echo "This is first step"

      - name : Get Code 
        uses: actions/checkout@v4

      - name: Get npm install 
        uses: actions/setup-node@v4
        with: 
           node-version: 18
  secondjob:
    needs: myjob
    runs-on: ubuntu-latest
    steps: 
      - name : Print Second Message 
        run: echo "this is second Message"
      
      - name: Get npm install 
        uses: actions/setup-node@v4
        with: 
           node-version: 18
  
      

      